# Generated by Django 3.1 on 2020-10-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_choice_is_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_vote',
            field=models.BooleanField(default=False),
        ),
    ]
