# Generated by Django 3.1 on 2020-10-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_vote_is_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_vote',
            field=models.CharField(default='', max_length=200),
        ),
    ]
