# Generated by Django 3.1 on 2020-10-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_question_last_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_vote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='is_vote',
        ),
    ]
